project:
  type: website

website:
  title: "Mathe kapieren mit Python"
  sidebar:
    style: docked
    search: true
    contents: auto

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-tools: true
    code-annotations: below

execute:
  cache: true
  freeze: auto
